config/routes.rb
Rails.application.routes.draw do

    scope "/:locale", locale: /#{I18n.available_locales.join('|')}/ do


                    root 'page#index'

                    # PAGES
                    get 'entreprise', to: "page#entreprise"
                    get 'equipe', to: "page#equipe"

                    # Pages > Carriere
                    get 'carrieres', to: "page#carrieres"
                    get 'poste', to: "page#fiche_poste"

                    get 'candidature', to: "page#candidature"
                    post 'candidature', to: "contact#candidature_send", as: "candidature_send"
                    get 'candidature-spontanee', to: "page#candidature_spontanee"
                    post 'candidature-spontanee', to: "contact#candidature_spontanee_send", as: "candidature_spontanee_send"

                    # Contact
                    get 'contact/success', to: "contact#success"
                    get 'contact/error', to: "contact#error"
                    get 'contact', to: "contact#general"
                    post 'contact/general', to: "contact#general_send", as:"general_send"

                    get 'contact/acquisition-equipement',   to: "contact#acquisition_equipement"
                    post 'contact/acquisition-equipement',  to: "contact#acquisition_equipement_send",  as:"acquisition_equipement_send"
                    get 'contact/inspection-technique',     to: "contact#inspection_technique"
                    post 'contact/inspection-technique',    to: "contact#inspection_technique_send",    as:"inspection_technique_send"

                    get 'contact/evaluation-equipement',    to: "contact#evaluation_equipement"
                    post 'contact/evaluation-equipement',   to: "contact#evaluation_equipement_send",    as:"evaluation_equipement_send"

                    get 'contact/echange-equipement/(:id)', to: "contact#echange_equipement", as: "contact/echange/equipement/"
                    post 'contact/echange-equipement/(:id)',   to: "contact#echange_equipement_send",    as:"echange_equipement_send"


                    get 'contact/ajustement-equipement/',   to: "contact#ajustement_equipement"
                    post 'contact/ajustement-equipement',   to: "contact#ajustement_equipement_send",   as:"ajustement_equipement_send"
                    get 'contact/demande-financement',      to: "contact#demande_financement"
                    post 'contact/demande-financement',     to: "contact#demande_financement_send",     as:"demande_financement_send"
                    post 'contact/estimation-transport',    to: "contact#estimation_transport_send",    as:"estimation_transport_send"
                    get 'contact/recherche-approfondie',    to: "contact#recherche_approfondie"
                    post 'contact/recherche-approfondie',   to: "contact#recherche_approfondie_send",    as:"recherche_approfondie_send"

                    # SERVICES

                    get 'services', to: "services#index"
                    get 'financement', to: "page#financement"

                    # Services > Pieces
                    get 'pieces', to:"services#pieces"
                    get 'pieces/commande-libre', to:"services#pieces_commande_libre"
                    post 'pieces/commande', to:"services#pieces_commande_send", as: "pieces/commande"
                    get 'pieces/recherche-approfondie', to:"services#pieces_recherche_approfondie"


                    # Services > equipements
                    get 'equipements', to:"services#equipements"
                    get 'equipements/neufs', to:"services#equipements_neufs"
                    get 'equipements/neufs/marques/', to:"services#equipements_neufs_marques", as: 'equipements/neufs/marques'
                    get 'equipements/neufs/marque/(:marque)/', to:"services#equipements_neufs_marque", as: 'equipements/neufs/marque'
                    get 'equipements/neufs/type/(:type)', to:"services#equipements_neufs_type", as: 'equipements/neufs/type'
                    get 'equipements/neufs/culture/(:culture)/', to:"services#equipements_neufs_culture", as: 'equipements/neufs/culture'
                    get 'equipements/usages', to:"services#equipements_usages"
                    get 'equipements/usages/evaluation', to:"services#equipements_usages_evaluation"
                    get 'equipements/usages/fiche/(:id)/(:marque)/(:annee)', to:"services#equipements_usages_fiche", as: 'equipements/usages/fiche'

                    # Services > expertise-conseil
                    get 'expertise', to:"services#expertise_conseil"
                    get 'expertise/acquisition-equipement', to:"services#acquisition_equipement"
                    get 'expertise/inspection-technique', to:"services#inspection_technique"
                    get 'expertise/ajustement-equipement', to:"services#ajustement_equipement"
                    get 'expertise/evaluation-equipement', to:"services#evaluation_equipement"

                    # Services > Transport
                    get 'transport', to:"services#transport"
                    get 'transport/transport-machinerie', to:"services#transport_machinerie", as: "transport/transport-machinerie"
                    get 'transport/transport-international', to:"services#transport_international", as: "transport/transport-international"
                    get 'transport/transport-hors-normes', to:"services#transport_hors_normes", as: "transport/transport-hors-normes"

                    # LANDING PAGES

                    get '/landing/(:year)/(:landing_page)/', to: "page#landing_page", as: 'landing'

        
        end

        root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

        # Redirection de toutes les URL avec la locale (FR|EN)
        get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
                      constraints: { path: /(?!(#{I18n.available_locales.join("|")})\/).*/, subdomain: '' },
                      format: false




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navigation.html.erb
<header>
    <div class="grid-container container_navigation">
        <div class="mobile-logo show-for-small-only">
            <div class="grid-x">
                <div class="cell">

                    <%= link_to root_path,class:"logo logo_nav" do %>
                        LAVOIE EQUIPEMENT
                    <% end %>
                </div>
                <div class="cell">
                    <span class="phone">418-247-5955</span>
                </div>
            </div>
        </div>
        <div class="title-bar" data-responsive-toggle="menu-principal" data-hide-for="medium">
             <button class="menu-icon" type="button" data-toggle></button>
            <div class="title-bar-title"> &nbsp; Menu principal</div>
            <span class="langue_switcher">
                <%= link_to  "Français", request.domain ? request.fullpath.sub!('en','fr') : request.fullpath.sub!('/en/','/fr/') %> | <%= link_to "English" , request.domain ? request.fullpath.sub!('fr','en') : request.fullpath.sub!('/fr/','/en/') %>
            </span>
        </div>
        <div class="top-bar" id="menu-principal">
            <div class="top-bar-title">
                <%= link_to root_path,class:"logo hide-for-small-only logo_nav" do %>
                    LAVOIE
                <% end %>
            </div>
            <div class="top-bar-right">
                <ul class="vertical medium-horizontal menu" data-responsive-menu="drilldown medium-dropdown" data-back-button="<li class='js-drilldown-back'><a>Retour</a></li>" >
                  <li><%= link_to "L'entreprise", entreprise_url() %></li>
                  <li class="hide-for-small-only"><%= link_to "Nos services", services_url() %></li>
                  <li class="show-for-small-only"><%= link_to "Nos services", services_url() %>
                      <ul class="menu vertical hide-for-large">
                        <li><strong><%= link_to  "Expertise-Conseil",expertise_url %></strong>    </li>
                        <li><strong><%= link_to  "Equipements Agricole",equipements_url %></strong></li>
                        <li><strong><%= link_to  "Pièces et accessoires",pieces_url %></strong>    </li>
                        <li><strong><%= link_to  "Transport",transport_url %></strong></li>
                      </ul></li>
                  <li><%= link_to "Financement", financement_url() %></li>
                  <li><%= link_to "Contact", contact_url() %></li>
                    <li class="hide-for-small-only"><a href="#"><%= image_tag("earth.svg", width:16) %></a>
                        <ul class="menu vertical">
                          <li><%= link_to  "Français", request.domain ? request.fullpath.sub!('en','fr') : request.fullpath.sub!('/en/','/fr/') %></li>
                          <li><%= link_to "English" , request.domain ?  request.fullpath.sub!('fr','en') : request.fullpath.sub!('/fr/','/en/') %></li>
                        </ul>
                    </li>
                </ul>
              </div>

        </div>
    </div>
</header>