config/routes.rb
Rails.application.routes.draw do

    scope "/:locale", locale: /#{I18n.available_locales.join('|')}/ do


                    root 'page#index'

                    # PAGES
                    get 'entreprise', to: "page#entreprise"
                    get 'equipe', to: "page#equipe"

                    # Pages > Carriere
                    get 'carrieres', to: "page#carrieres"
                    get 'poste', to: "page#fiche_poste"

                    get 'candidature', to: "page#candidature"
                    post 'candidature', to: "contact#candidature_send", as: "candidature_send"
                    get 'candidature-spontanee', to: "page#candidature_spontanee"
                    post 'candidature-spontanee', to: "contact#candidature_spontanee_send", as: "candidature_spontanee_send"

                    # Contact
                    get 'contact/success', to: "contact#success"
                    get 'contact/error', to: "contact#error"
                    get 'contact', to: "contact#general"
                    post 'contact/general', to: "contact#general_send", as:"general_send"

                    get 'contact/acquisition-equipement',   to: "contact#acquisition_equipement"
                    post 'contact/acquisition-equipement',  to: "contact#acquisition_equipement_send",  as:"acquisition_equipement_send"
                    get 'contact/inspection-technique',     to: "contact#inspection_technique"
                    post 'contact/inspection-technique',    to: "contact#inspection_technique_send",    as:"inspection_technique_send"

                    get 'contact/evaluation-equipement',    to: "contact#evaluation_equipement"
                    post 'contact/evaluation-equipement',   to: "contact#evaluation_equipement_send",    as:"evaluation_equipement_send"

                    get 'contact/echange-equipement/(:id)', to: "contact#echange_equipement", as: "contact/echange/equipement/"
                    post 'contact/echange-equipement/(:id)',   to: "contact#echange_equipement_send",    as:"echange_equipement_send"


                    get 'contact/ajustement-equipement/',   to: "contact#ajustement_equipement"
                    post 'contact/ajustement-equipement',   to: "contact#ajustement_equipement_send",   as:"ajustement_equipement_send"
                    get 'contact/demande-financement',      to: "contact#demande_financement"
                    post 'contact/demande-financement',     to: "contact#demande_financement_send",     as:"demande_financement_send"
                    post 'contact/estimation-transport',    to: "contact#estimation_transport_send",    as:"estimation_transport_send"
                    get 'contact/recherche-approfondie',    to: "contact#recherche_approfondie"
                    post 'contact/recherche-approfondie',   to: "contact#recherche_approfondie_send",    as:"recherche_approfondie_send"

                    # SERVICES

                    get 'services', to: "services#index"
                    get 'financement', to: "page#financement"

                    # Services > Pieces
                    get 'pieces', to:"services#pieces"
                    get 'pieces/commande-libre', to:"services#pieces_commande_libre"
                    post 'pieces/commande', to:"services#pieces_commande_send", as: "pieces/commande"
                    get 'pieces/recherche-approfondie', to:"services#pieces_recherche_approfondie"


                    # Services > equipements
                    get 'equipements', to:"services#equipements"
                    get 'equipements/neufs', to:"services#equipements_neufs"
                    get 'equipements/neufs/marques/', to:"services#equipements_neufs_marques", as: 'equipements/neufs/marques'
                    get 'equipements/neufs/marque/(:marque)/', to:"services#equipements_neufs_marque", as: 'equipements/neufs/marque'
                    get 'equipements/neufs/type/(:type)', to:"services#equipements_neufs_type", as: 'equipements/neufs/type'
                    get 'equipements/neufs/culture/(:culture)/', to:"services#equipements_neufs_culture", as: 'equipements/neufs/culture'
                    get 'equipements/usages', to:"services#equipements_usages"
                    get 'equipements/usages/evaluation', to:"services#equipements_usages_evaluation"
                    get 'equipements/usages/fiche/(:id)/(:marque)/(:annee)', to:"services#equipements_usages_fiche", as: 'equipements/usages/fiche'

                    # Services > expertise-conseil
                    get 'expertise', to:"services#expertise_conseil"
                    get 'expertise/acquisition-equipement', to:"services#acquisition_equipement"
                    get 'expertise/inspection-technique', to:"services#inspection_technique"
                    get 'expertise/ajustement-equipement', to:"services#ajustement_equipement"
                    get 'expertise/evaluation-equipement', to:"services#evaluation_equipement"

                    # Services > Transport
                    get 'transport', to:"services#transport"
                    get 'transport/transport-machinerie', to:"services#transport_machinerie", as: "transport/transport-machinerie"
                    get 'transport/transport-international', to:"services#transport_international", as: "transport/transport-international"
                    get 'transport/transport-hors-normes', to:"services#transport_hors_normes", as: "transport/transport-hors-normes"

                    # LANDING PAGES

                    get '/landing/(:year)/(:landing_page)/', to: "page#landing_page", as: 'landing'

        
        end

        root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

        # Redirection de toutes les URL avec la locale (FR|EN)
        get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
                      constraints: { path: /(?!(#{I18n.available_locales.join("|")})\/).*/, subdomain: '' },
                      format: false




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/page/candidature.html.erb
<section class="intro_page">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <h1>Candidature</h1>
            </div>
        </div>
    </div>
</section>
<div class="cap_white">
<section class="content_page">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">

                <h3>Proposer votre candidature</h3>
                <%= form_tag(candidature_send_path, method: "post",multipart: true) do %>

                    <%= label_tag(:name, "Votre nom") %>
                    <%= text_field_tag :name, nil, {placeholder: "Votre nom", required: true} %>

                    <%= label_tag(:email, "Votre courriel") %>
                    <%= email_field_tag :email, nil, {placeholder: "Votre adresse courriel", required: true} %>
                    <%=
                    select_tag(:poste, options_for_select([
                        ['Mécanicien agricole'],
                        ['Commis au pièces'],
                        ['Contrôleur(se) financier']
                      ]), :include_blank => '-- Nom du poste --', required: true)
                    %>
                    <%= label_tag(:cv, "Curriculum Vitae") %>
                    <%= file_field_tag 'cv_candidature', required: true%>

                    <%= label_tag(:cv, "Lettre de présentation") %>
                    <%= file_field_tag 'lettre_candidature', required: true %>

                    <%= submit_tag "Envoyer votre message", class:"button large"%>

                <% end %>

                <br>
                <p class="callout primary">
                    <strong>Seules les candidatures retenues seront recontactées pour passer un entretien</strong>
                </p>

            </div>
        </div>
    </div>
</section>

app/views/page/candidature_spontanee.html.erb
<section class="intro_page">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <h1>Candidature spontanée</h1>
            </div>
        </div>
    </div>
</section>
<div class="cap_white">
<section class="content_page content_formulaire">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <div class="card_formulaire">

                <h3>Proposer votre candidature</h3>

                <%= form_tag(candidature_spontanee_send_path, method: "post",multipart: true) do %>

                    <%= label_tag(:name, "Votre nom") %>
                    <%= text_field_tag :name, nil, {placeholder: "Votre nom", required: true} %>

                    <%= label_tag(:email, "Votre courriel") %>
                    <%= email_field_tag :email, nil, {placeholder: "Votre adresse courriel", required: true} %>

                    <%= label_tag(:message, "Votre message") %>
                    <%= text_area_tag :message,nil, {placeholder: "Votre message",rows: 10, cols: 25, required: true} %>

                    <%= label_tag(:cv, "Curriculum Vitae") %>
                    <%= file_field_tag 'cv_candidature', required: true%>

                    <%= label_tag(:cv, "Lettre de présentation") %>
                    <%= file_field_tag 'lettre_candidature', required: true %>

                    <%= submit_tag "Envoyer votre message", class:"button large"%>

                <% end %>

                <br>
                <p>
                    <small>Seules les candidatures retenues seront recontactées pour passer un entretien</small>
                </p>

            </div>
            </div>
        </div>
    </div>
</section>

app/views/page/carrieres.fr.html.erb
<section class="intro_page">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <h1>Carrières</h1>
            </div>
        </div>
    </div>
</section>

<div class="cap_white"></div>

<section class="content_page">
    <div class="grid-container">
        <div class="grid-x grid-margin-y">
            <div class="cell large-12">
                <h2>Pourquoi LAVOIE?</h2>
                <p>Malgré c'est 30 ans d'existance, LAVOIE Équipement est toujours une entreprise en pleine croissance.
                    Que ce soit par l'évolution de la demande et du marché, des défis techniques ou bien par l'innovation, l'entreprise
                    se renouvelle en permanence. C'est inscrit dans l'ADN. Les personnes qui y travaillent repoussent sans cesses les limites.
                    En choississant LAVOIE, vous choississez de vous mettre au défi et d'évoluer dans votre carrière. Nous vous accompagnons dans cette évolution.
                </p>
            </div>

            <div class="cell large-4">
                <h3>Explorer votre potentiel</h3>
                <ul>
                    <li>Formation continue</li>
                    <li>Outils selon vos besoins</li>
                    <li>Autonomie et liberté d'actions</li>
                </ul>

            </div>

                <div class="cell large-4">
                    <h3>Respecter votre équilibre de vie</h3>
                    <ul>
                        <li>Horaire de travail flexible</li>
                        <li>Journée de congés pour les imprévus</li>
                        <li>Travail à distance</li>
                    </ul>
                </div>

                <div class="cell large-4">
                    <h3>Des avantages sociaux</h3>
                    <ul>
                        <li>Bonification du salaire selon niveau d’anglais</li>
                        <li>RVER avec cotisation de l’employeur</li>
                        <li>Activités sociales (BBQ, Cabane à sucre et plus)</li>
                    </ul>


                </div>

            </div>
        </div>
    </div>
</section>

<section class="content_page postes_ouverts">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">

                <h2>Ce que nous cherchons</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            </div>
        </div>
    </div>
</section>
<section class="content_page postes_ouverts">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">

                <h2>Les postes ouverts</h2>
                <ul>
                    <li> <%= link_to "Mécanicien(ne) agricole", poste_url %> </li>
                    <li>Contrôleur(se) financier</li>
                    <li>Commis(e) aux pièces</li>
                </ul>
            </div>
        </div>
    </div>
</section>

<section class="cta_page">
    <div class="grid-container">
        <div class="grid-x grid-margin-x grid-margin-y">
            <div class="cell large-12">
                <h3>Nous recherchons tout type de profil!</h3>
                <p>
                    Aucuns des postes ne semble vous correspondre?
                    Notre entreprise évolue et nos besoins aussi!
                </p>
                <br>
                <p>
                    <%= link_to "Candidature spontanée", candidature_spontanee_url, class: "button large" %>
                </p>
        </div>
    </div>
</section>

app/views/page/entreprise.fr.html.erb
<section class="intro_page intro_entreprise">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <h1>L'entreprise LAVOIE</h1>
            </div>
        </div>
    </div>
</section>

<div class="cap_white">

<section class="content_page bg_dust">
    <div class="grid-container">

        <div class="grid-x grid-margin-x grid-margin-y">

            <div class="cell large-12">
                <h2 class="hero">Une histoire de famille</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    empor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
                    veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
                     ea commodo consequat. Duis aute irure dolor in reprehenderit in volup
                  </p>
            </div>
        </div>

        <div class="grid-x grid-margin-x grid-margin-y">
            <div class="cell large-4">
                <img src="http://placehold.it/550" alt="">
            </div>
            <div class="cell large-4">
                <img src="http://placehold.it/550" alt="">
            </div>
            <div class="cell large-4">
                <img src="http://placehold.it/550" alt="">
            </div>
        </div>

    </div>
</section>

<div class="cap_gray"></div>

<section class="content_page_dark content_notre_adn ">
    <div class="grid-container spacer_bottom">
        <div class="grid-x grid-margin-x grid-margin-y">
            <div class="cell">
                <h2 class="section">Notre ADN</h2>
            </div>
            <div class="cell large-4">
                <h3>Passion</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod  velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
            <div class="cell large-4">
                <h3>Rigueur</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
            <div class="cell large-4">
                <h3>Expertise</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
        </div>
    </div>
</section>
<div class="cap_white"></div>
<section class="content_page no_bg evolution">
    <div class="grid-container">

        <div class="grid-x">
            <div class="cell large-12">
                <h2 class="hero">Evolution</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
        </div>
    </div>
</section>
<section class="content_page no_bg implications">
    <div class="grid-container">

        <div class="grid-x">
            <div class="cell large-12">
                <h2 class="hero">Implications sociales</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
        </div>
    </div>
</section>
<section class="content_page no_bg entreprise_aujourdhui">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell large-12">
                <h2 class="hero">L'entreprise aujourd'hui</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
        </div>
    </div>
</section>



<section class="cta_page">
    <div class="grid-container">
        <div class="grid-x grid-margin-x grid-margin-y">
            <div class="cell large-12">
                <h3>Venez nous rencontrer!</h3>
                <p>
                    Vous souhaitez visitez nos installations ou rencontrer un membre de <strong><%= link_to "l'équipe LAVOIE?", equipe_url() %></strong> il nous fera
                    plaisir de vous rencontrer et répondre à vos questions!
                </p>
                <br>
                <p>
                    <%= link_to "Contactez-nous!", contact_url, class: "button large" %>
                </p>
        </div>
    </div>
</section>

app/views/page/equipe.fr.html.erb
<section class="intro_page intro_equipe">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <h1>L'Équipe LAVOIE</h1>
            </div>
        </div>
    </div>
</section>
<div class="cap_white">

<section class="content_page content_equipe bg_dust">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell large-6 texte_departement">
                <div>

                <h2>Mécanique</h2>
                <p>
                    Avec plus de 30 ans d'expérience de réparations et d'ajustements de machines agricoles,
                    le département mécanique est au coeur des opérations de l'entreprise. Du nettoyage à l'ajustement,
                    nous maîtrisons tout les aspects de votre équipement.
                </p>
            </div>
            </div>
            <div class="cell large-6">
                <%= image_tag("departement_mecanique.png") %>
            </div>
        </div>

        <div class="grid-x">
            <div class="cell large-6">
                <%= image_tag("departement_pieces.png") %>
            </div>
            <div class="cell large-6 texte_departement">
            <div>
                <h2>Pièces</h2>
                <p>
                    Que vous soyez à la recherche d'une simple pièce ou d'un élément très spécifique, les spécialistes de
                    ce département sauront vous trouvez ce qu'il vous faut! Travaillant en direct avec le garage,
                    le département des pièces s'assure également de l'approvisionnemnt pour les réparations d'équipements.
                </p>
            </div>
            </div>
        </div>

        <div class="grid-x">

            <div class="cell large-6 texte_departement">
                <div>
                    <h2>Transport</h2>
                    <p>
                        Transportez des équipements agricole à l'intérieur et à l'extérieur de la province en toute sécurité et conformité avec les lois, c'est le rôle de ce département!
                        Une expertise de la logistique couplée à une gestion de projet rigoureuse font que chaque transport est un succès pour le client et pour notre entreprise.
                    </p>
                </div>
            </div>
            <div class="cell large-6">
                <%= image_tag("departement_transport.png") %>
            </div>
        </div>

        <div class="grid-x">
            <div class="cell large-6">
                <%= image_tag("departement_administration.png") %>
            </div>
            <div class="cell large-6 texte_departement">
                <div>
                    <h2>Administration</h2>
                    <p>
                        Le département administration est un véritable socle pour les autres départements.
                        Que ce soit la direction, les ressources humaines, la comptabilité ou bien les technologies de l'information.
                        ils s'assurent tous du bon fonctionnement de l'entreprise ainsi que de la
                        satisfaction de notre tous nos clients.
                    </p>
                </div>
            </div>
        </div>

    </div>
</section>


<section class="content_page valeurs_equipe">
    <div class="grid-container">
        <div class="grid-x grid-margin-x">
            <div class="cell large-6 texte_valeurs">
                <div>
                    <h2 class="hero">Ce qui nous unis chez LAVOIE</h2>
                    <p>
                        Ce qui fait que LAVOIE Équipement est une équipe n'est pas les compétences variées, les différences ou de génération des personnes, ni les origines ou
                        langues parlées mais bien les valeurs auxquelles adhèrent d'une façon unanime, les membres qui la compose.
                    </p>
                    <br>
                    <p><strong>Avons-nous des valeurs en commun?</strong>
                    <p> <%= link_to "Appliquer chez LAVOIE", carrieres_url, class:"button large" %> </p>
                </div>
            </div>
            <div class="cell large-6">
                <%= image_tag('valeurs_equipe.png') %>
            </div>
        </div>
    </div>
</section>

app/views/page/index.fr.html.erb
<section class="hero">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <h1>Lavoie Equipement,<br> votre partenaire agricole</h1>
            </div>
        </div>
    </div>
</section>


<div class="cap_black"></div>

<section class="navigation">
    <div class="grid-container">

        <div class="grid-x grid-margin-x grid-margin-y">
            <div class="cell large-auto medium-6 small-12">
                <h2><%= link_to "Expertise", expertise_url %></h2>
                <ul>
                    <li><%= link_to "Acquisition d'équipements", expertise_acquisition_equipement_url %></li>
                    <li><%= link_to "Inspection technique", expertise_inspection_technique_url %></li>
                    <li><%= link_to "Ajustement au champ", expertise_ajustement_equipement_url %></li>
                    <li><%= link_to "Évaluation d'équipement", expertise_evaluation_equipement_url%></li>
                </ul>
            </div>

        <div class="cell large-auto medium-6 small-12">
            <h2><%= link_to "équipements", equipements_url %></h2>
            <ul>
                <li><%= link_to "Équipements neufs", equipements_neufs_url %></li>
                <li><%= link_to "Équipements usagés", equipements_usages_url %></li>
            </ul>
        </div>
        <div class="cell large-auto medium-6 small-12">
            <h2><%= link_to "pièces", pieces_url %></h2>
            <ul>
                <li><%= link_to "Catalogues constructeurs", pieces_commande_libre_url %></li>
                <li><%= link_to "Recherche approfondie", pieces_recherche_approfondie_url %></li>
            </ul>
        </div>

        <div class="cell large-auto medium-6 small-12">
            <h2><%= link_to "transport", transport_url %></h2>
            <ul>
                <li><%= link_to "Transport de machinerie", transport_transport_machinerie_url %></li>
                <li><%= link_to "Transport  international", transport_transport_international_url %></li>
                <li><%= link_to "Transport Hors-normes", transport_transport_hors_normes_url %></li>
            </ul>
        </div>
        </div>

      </div>
</section>
<div class="cap_white"></div>

<section class="brands">
    <div class="grid-container">
            <div class="grid-x grid-margin-x grid-margin-y">

              <div class="cell large-5 medium-12 small-12 brand_title">
                  <h3><strong>Nous distribuons toutes les marques d'équipements</strong> </h3>
              </div>

              <div class="cell auto large-offset-1">
                  <div class="grid-x grid-margin-x medium-up-3">

                        <div class="cell">
                            <%= link_to equipements_neufs_marque_url(marque: "macdon") do %>
                            <%= image_tag("logo/logo_macdon.png") %>
                            <% end %>
                        </div>
                      <div class="cell">
                          <%= link_to equipements_neufs_marque_url(marque: "antonio-carraro") do %>
                         <%= image_tag("logo/logo_antonio_carraro.png") %>
                         <% end %>
                      </div>
                      <div class="cell">
                          <%= link_to equipements_neufs_marque_url(marque: "harvestmore") do %>
                            <%= image_tag("logo/logo_harvestmore.png") %>
                          <% end %>
                      </div>
                      <div class="cell">
                          <%= link_to equipements_neufs_marque_url(marque: "john-deere") do %>
                          <%= image_tag("logo/logo_john_deere.png") %>
                          <% end %>
                      </div>
                      <div class="cell">
                          <%= link_to equipements_neufs_marque_url(marque: "new-holland") do %>
                          <%= image_tag("logo/logo_new_holland.png") %>
                          <% end %>
                      </div>
                      <div class="cell flex_center">
                          <div>
                          <p class="center">
                              <strong>
                                  <%= link_to "Voir toutes les marques", equipements_neufs_marques_url, class:"center" %>
                              </strong>
                          </p>
                      </div>
                      </div>
                  </div>
              </div>
          </div>
    </div>
</section>

<section class="contact">
    <div class="grid-container">
        <div class="grid-x grid-margin-x grid-margin-y">
            <div class="cell large-12">
                <h2 class="section">30 ans d'expertise à votre service</h2>
                <p>
                    Depuis plus de 30 ans, Lavoie équipement a acquis les connaissances et l'expérience nécessaire pour vous donner le meilleur service possible.
                    <br>
                    Que ce soit pour des conseils, de l'équipement agricole, des pièces ou du transport, nous répondons à vos questions! <strong>Appelez-nous!</strong>
                </p>
                <p>
                    <br>
                    <a href="tel:4812475955" class="button large"><strong>418-247-5955</strong></a>
                </p>
            </div>
        </div>
    </div>
</section>