config/routes.rb
Rails.application.routes.draw do

    scope "/:locale", locale: /#{I18n.available_locales.join('|')}/ do


                    root 'page#index'

                    # PAGES
                    get 'entreprise', to: "page#entreprise"
                    get 'equipe', to: "page#equipe"

                    # Pages > Carriere
                    get 'carrieres', to: "page#carrieres"
                    get 'poste', to: "page#fiche_poste"

                    get 'candidature', to: "page#candidature"
                    post 'candidature', to: "contact#candidature_send", as: "candidature_send"
                    get 'candidature-spontanee', to: "page#candidature_spontanee"
                    post 'candidature-spontanee', to: "contact#candidature_spontanee_send", as: "candidature_spontanee_send"

                    # Contact
                    get 'contact/success', to: "contact#success"
                    get 'contact/error', to: "contact#error"
                    get 'contact', to: "contact#general"
                    post 'contact/general', to: "contact#general_send", as:"general_send"

                    get 'contact/acquisition-equipement',   to: "contact#acquisition_equipement"
                    post 'contact/acquisition-equipement',  to: "contact#acquisition_equipement_send",  as:"acquisition_equipement_send"
                    get 'contact/inspection-technique',     to: "contact#inspection_technique"
                    post 'contact/inspection-technique',    to: "contact#inspection_technique_send",    as:"inspection_technique_send"

                    get 'contact/evaluation-equipement',    to: "contact#evaluation_equipement"
                    post 'contact/evaluation-equipement',   to: "contact#evaluation_equipement_send",    as:"evaluation_equipement_send"

                    get 'contact/echange-equipement/(:id)', to: "contact#echange_equipement", as: "contact/echange/equipement/"
                    post 'contact/echange-equipement/(:id)',   to: "contact#echange_equipement_send",    as:"echange_equipement_send"


                    get 'contact/ajustement-equipement/',   to: "contact#ajustement_equipement"
                    post 'contact/ajustement-equipement',   to: "contact#ajustement_equipement_send",   as:"ajustement_equipement_send"
                    get 'contact/demande-financement',      to: "contact#demande_financement"
                    post 'contact/demande-financement',     to: "contact#demande_financement_send",     as:"demande_financement_send"
                    post 'contact/estimation-transport',    to: "contact#estimation_transport_send",    as:"estimation_transport_send"
                    get 'contact/recherche-approfondie',    to: "contact#recherche_approfondie"
                    post 'contact/recherche-approfondie',   to: "contact#recherche_approfondie_send",    as:"recherche_approfondie_send"

                    # SERVICES

                    get 'services', to: "services#index"
                    get 'financement', to: "page#financement"

                    # Services > Pieces
                    get 'pieces', to:"services#pieces"
                    get 'pieces/commande-libre', to:"services#pieces_commande_libre"
                    post 'pieces/commande', to:"services#pieces_commande_send", as: "pieces/commande"
                    get 'pieces/recherche-approfondie', to:"services#pieces_recherche_approfondie"


                    # Services > equipements
                    get 'equipements', to:"services#equipements"
                    get 'equipements/neufs', to:"services#equipements_neufs"
                    get 'equipements/neufs/marques/', to:"services#equipements_neufs_marques", as: 'equipements/neufs/marques'
                    get 'equipements/neufs/marque/(:marque)/', to:"services#equipements_neufs_marque", as: 'equipements/neufs/marque'
                    get 'equipements/neufs/type/(:type)', to:"services#equipements_neufs_type", as: 'equipements/neufs/type'
                    get 'equipements/neufs/culture/(:culture)/', to:"services#equipements_neufs_culture", as: 'equipements/neufs/culture'
                    get 'equipements/usages', to:"services#equipements_usages"
                    get 'equipements/usages/evaluation', to:"services#equipements_usages_evaluation"
                    get 'equipements/usages/fiche/(:id)/(:marque)/(:annee)', to:"services#equipements_usages_fiche", as: 'equipements/usages/fiche'

                    # Services > expertise-conseil
                    get 'expertise', to:"services#expertise_conseil"
                    get 'expertise/acquisition-equipement', to:"services#acquisition_equipement"
                    get 'expertise/inspection-technique', to:"services#inspection_technique"
                    get 'expertise/ajustement-equipement', to:"services#ajustement_equipement"
                    get 'expertise/evaluation-equipement', to:"services#evaluation_equipement"

                    # Services > Transport
                    get 'transport', to:"services#transport"
                    get 'transport/transport-machinerie', to:"services#transport_machinerie", as: "transport/transport-machinerie"
                    get 'transport/transport-international', to:"services#transport_international", as: "transport/transport-international"
                    get 'transport/transport-hors-normes', to:"services#transport_hors_normes", as: "transport/transport-hors-normes"

                    # LANDING PAGES

                    get '/landing/(:year)/(:landing_page)/', to: "page#landing_page", as: 'landing'

        
        end

        root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

        # Redirection de toutes les URL avec la locale (FR|EN)
        get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
                      constraints: { path: /(?!(#{I18n.available_locales.join("|")})\/).*/, subdomain: '' },
                      format: false




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

    def index
    end

    # EXPERTISE-CONSEIL
    # --------------------------------------------------------------------------

    def expertise_conseil
        render "services/expertise/expertise_conseil"
    end

    def acquisition_equipement
        render "services/expertise/acquisition_equipement"
    end

    def inspection_technique
        render "services/expertise/inspection_technique"
    end

    def ajustement_equipement
        render "services/expertise/ajustement_equipement"
    end
    def evaluation_equipement
        render "services/expertise/evaluation_equipement"
    end

    # EQUIPEMENT
    # --------------------------------------------------------------------------

    def equipements
        render "services/equipements/equipements"
    end

    # Equipements neufs

    def equipements_neufs
        render "services/equipements/equipements_neufs"
    end

    def equipements_neufs_marques
        render "services/equipements/equipements_neufs"
    end
    def equipements_neufs_marque
        @marque = params[:marque]
        render "services/equipements/marques/fiche_marque" rescue equipements_neufs_marques
    end

    def equipements_neufs_type
        @type = params[:type]
        render "services/equipements/types/fiche_type" rescue equipements_neufs
    end

    def equipements_neufs_culture
        @culture = params[:culture]
        render "services/equipements/cultures/culture_" + @culture rescue equipements_neufs
    end

    # Equipements usagés

    def equipements_usages
        if params.has_key?(:search) && !params[:search].empty? || params.has_key?(:brand) && !params[:brand].empty?
            @equipments = Equipment.with_attached_photos.search(params[:brand],params[:search].downcase)
            @search = true
        else
            @equipments = Equipment.with_attached_photos.all
            @search = false
        end

        render "services/equipements/equipements_usages"
    end

    def equipements_usages_fiche
        @equipment = Equipment.with_attached_photos.find(equipements_usages_params[:id])
        render "services/equipements/equipements_usages_fiche"
    end

    def equipements_usages_evaluation
        render "services/equipements/equipements_usages_evaluation"
    end

    # PIECES
    # --------------------------------------------------------------------------

    def pieces
        render "services/pieces/pieces"
    end

    def pieces_commande_libre

        @marques = Array.new
        @marques = {
                    'Macdon'            => "https://www.macdon.com/support/parts-catalogs",
                    'Horst'             => "http://horstwelding.ricambio.net/site/pagece5.wplus?ID_COUNT=ce_5_home&LN=2&CEPV=Horstwelding001&CELN=2&CEME=2&NDS=CE_1&PRF=1&PRNDS=R&PRC=%7CR%7CCE_1&KPRD=CE_1#CE_1",
                    #'Harvestmore'       => "#",
                    #'Grecav'            => "#",
                    'John Deere'        => "http://jdpc.deere.com/jdpc/servlet/com.deere.u90490.partscatalog.view.servlets.HomePageServlet_Alt?Origin=JDParts",
                    'New Holland'       => "https://partstore.agriculture.newholland.com/us/parts-search.html?csid=7d048ad87a81fc88052ed34ebfa8e724&sl=EN&currency=#epc::home",
                    'Claas'             => "http://www.claas.fr/service_pieces/catalogue/catalogue-des-pieces-de-rechange-parts-doc-online",
                    'Case IH'           => "https://partstore.caseih.com/us/index.php?target=epc_manuals_detail&sl=FR&csid=28171f8d6720eef273b5aff0affe2148&sl=FR&currency=#epc::home",
                    'Laverda'           => "https://ngpc.cnh.com/Lp/es/cbs?brand=NHAG&region=EUR&sma=&locale=fr",
                    'Schumacher'        => "https://www.argis2000.ca/schumacher-llc/",
                    'A&I'               => "https://www.allpartsstore.com/fr/index.htm?customernumber=PQ3773",
                    'Massey Ferguson'   => "http://www.agcopartsbooks.com/PartsBooksN/Login.aspx?ReturnUrl=%2fPartsBooksN%2fViewer%2fDefault.aspx",
                }

        @parts_order = PartsOrder.new
        @parts_order.parts_order_items.build
        render "services/pieces/pieces_commande_libre"
    end

    def pieces_commande_send

        @parts_order = PartsOrder.new(parts_order_params)
        if @parts_order.save

            # Envoi courriel au département des pièces
            @message = {
                            name: @parts_order.name,
                            email: @parts_order.email,
                            ip_address: request.remote_ip,
            }
            ContactMailer.commande_libre(@message,@parts_order).deliver
            render "services/pieces/confirmation_commande_libre"
        else
            # Envoi courriel au service TI
            ContactMailer.notification_ti("commande libre", "Impossible de sauvegarder la commande libre").deliver
            render "services/pieces/erreur_commande_libre"
        end

    end

    def pieces_recherche_approfondie
        render "services/pieces/pieces_recherche_approfondie"
    end


    # TRANSPORT
    # --------------------------------------------------------------------------

    def transport
        render "services/transport/transport"
    end

    def transport_machinerie
        render "services/transport/transport_machinerie"
    end

    def transport_international
        render "services/transport/transport_international"
    end

    def transport_hors_normes
        render "services/transport/transport_hors_normes"
    end

    # --------------------------------------------------------------------------
    # PRIVATE
    # --------------------------------------------------------------------------

    private

    def equipements_usages_params
        params.permit(:id)
    end

    def parts_order_params
        params.require(:parts_order).permit(
            :name,
            :email,
            :phone,
            parts_order_items_attributes: [:marque, :reference, :quantite, :_destroy])
    end

end

app/views/services/equipements/equipements.fr.html.erb
<section class="intro_page header_page intro_equipement">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <h1>Equipements agricole</h1>
            </div>
        </div>
    </div>
</section>

<div class="cap_white"></div>

<section class="content_page">
    <div class="grid-container">
        <div class="grid-x grid-margin-x spacer_bottom">
            <div class="cell large-offset-2 large-4 center">
                <h2>Equipements neufs</h2>
                <br>
                <%= link_to  equipements_neufs_url do  %>
                    <%= image_tag('equipement_neufs.png') %>
                <% end %>
            </div>
            <div class="cell large-4 center">
                <h2>Equipements usagés</h2>
                <br>
                <%= link_to  equipements_usages_url do  %>
                    <%= image_tag('equipement_usages.png') %>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/services/equipements/equipements_neufs_old.html.erb
<section class="intro_page header_page intro_equipement">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <h1>Equipements neufs</h1>
            </div>
        </div>
    </div>
</section>

<div class="cap_white"></div>

<section class="content_page center">

    <h3>Par marque</h3>
    <br>
    <div class="grid-container">
            <div class="grid-x grid-margin-x grid-margin-y small-up-2 medium-up-6 ">


            <div class="cell">
                <%= link_to equipements_neufs_marque_url(marque:"macdon") do %>
                <%= image_tag("logo/logo_macdon.png") %>
                <% end %>
            </div>
            <div class="cell">
                <%= link_to equipements_neufs_marque_url(marque:"antonio-carraro") do %>
             <%= image_tag("logo/logo_antonio_carraro.png") %>
             <% end %>
            </div>
            <div class="cell">
                <%= link_to equipements_neufs_marque_url(marque:"grecav") do %>
                    <%= image_tag("logo/logo_grecav.png") %>
                <% end %>
            </div>
            <div class="cell">
                <%= link_to equipements_neufs_marque_url(marque:"harvestmore") do %>
                 <%= image_tag("logo/logo_harvestmore.png") %>
                <% end %>
            </div>
            <div class="cell">
                <%= link_to equipements_neufs_marque_url(marque:"horst") do %>
                    <%= image_tag("logo/logo_horst.png") %>
                <% end %>
            </div>
            <div class="cell">
                <%= link_to equipements_neufs_marque_url(marque:"mudhog") do %>
                 <%= image_tag("logo/logo_mudhog.png") %>
                 <% end %>
            </div>
        </div>

    <p><br><strong><%= link_to "Voir toutes les marques",equipements_neufs_marques_url %></strong></p>
    </div>
</section>

<section class="content_page_light center">
    <div class="grid-container">
    <h3>Par type d'équipement</h3>
    <div class="grid-container fluid">
        <div class="grid-x grid-margin-x">
            <div class="cell auto">
               <br>
               <%= link_to equipements_neufs_type_url(type:"moissonneuse-batteuse") do %>
                    <%= image_tag  "http://placehold.it/250" %>
                    <br>
                    <br>
                    <h4>Moissonneuse-Batteuse</h4>
                <% end %>
            </div>
           <div class="cell auto">
               <br>
               <%= link_to equipements_neufs_type_url(type:"andaineuse-automotrice") do %>
                <%= image_tag  "http://placehold.it/250" %>
                <br>
                <br>
                <h4>Andaineuse automotrice</h4>
                <% end %>
            </div>
           <div class="cell auto">
               <br>
               <%= link_to equipements_neufs_type_url(type:"faucheuse") do %>
                <%= image_tag  "http://placehold.it/250" %>
                <br>
                <br>
                <h4>Faucheuse</h4>
                <% end %>
            </div>
           <div class="cell auto">
               <br>
               <%= link_to equipements_neufs_type_url(type:"tracteur") do %>
                <%= image_tag  "http://placehold.it/250" %>
                <br>
                <br>
                <h4>Tracteur</h4>
                <% end %>
            </div>
           <div class="cell auto">
               <br>
               <%= link_to equipements_neufs_type_url(type:"tables") do %>
                <%= image_tag  "http://placehold.it/250" %>
                <br>
                <br>
                <h4>Tables</h4>
                <% end %>
            </div>
           <div class="cell auto">
               <br>
               <%= link_to equipements_neufs_type_url(type:"nez-a-mais") do %>
                <%= image_tag  "http://placehold.it/250" %>
                <br>
                <br>
                <h4>Nez à maïs</h4>
                <% end %>
            </div>
           <div class="cell auto">
               <br>
               <%= link_to equipements_neufs_type_url(type:"autre") do %>
                <%= image_tag  "http://placehold.it/250" %>
                <br>
                <br>
                <h4>Autre</h4>
                <% end %>
            </div>


        </div>
    </div>
</section>

<section class="content_page content_type_culture center">

    <h3>Par type de culture</h3>
    <br>
    <div class="grid-container">
        <div class="grid-x medium-up-3">
           <div class="cell">
                <%= link_to equipements_neufs_culture_url(culture: "ble") do %>
                <div class="vignette_culture">
                    <%= image_tag("vignette_ble.png", class: "image_culture") %>
                        <div class="overlay">
                            <div class="text">Blé</div>
                        </div>
                </div>
                <% end %>
            </div>
           <div class="cell">
                <%= link_to equipements_neufs_culture_url(culture: "mais") do %>
                <div class="vignette_culture">
                    <%= image_tag("vignette_mais.png", class: "image_culture") %>
                        <div class="overlay">
                            <div class="text">Maïs</div>
                        </div>
                </div>
                <% end %>
            </div>
           <div class="cell">
                <%= link_to equipements_neufs_culture_url(culture: "soya") do %>
                <div class="vignette_culture">
                    <%= image_tag("vignette_soya.png", class: "image_culture") %>
                        <div class="overlay">
                            <div class="text">Soya</div>
                        </div>
                </div>
                <% end %>
            </div>
           <div class="cell">
                <%= link_to equipements_neufs_culture_url(culture: "chanvre") do %>
                <div class="vignette_culture">
                    <%= image_tag("vignette_chanvre.png", class: "image_culture") %>
                        <div class="overlay">
                            <div class="text">Chanvre</div>
                        </div>
                </div>
                <% end %>
            </div>
           <div class="cell">
                <%= link_to equipements_neufs_culture_url(culture: "orge") do %>
                <div class="vignette_culture">
                    <%= image_tag("vignette_orge.png", class: "image_culture") %>
                        <div class="overlay">
                            <div class="text">Orge</div>
                        </div>
                </div>
                <% end %>
            </div>
           <div class="cell">
                <%= link_to equipements_neufs_culture_url(culture: "avoine") do %>
                <div class="vignette_culture">
                    <%= image_tag("vignette_avoine.png", class: "image_culture") %>
                        <div class="overlay">
                            <div class="text">Avoine</div>
                        </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</section>


<section class="cta_page">
    <div class="grid-container">
        <div class="grid-x grid-margin-x grid-margin-y">
            <div class="cell large-12">
                <h3>Toutes les marques n'auront pas la même efficacité!</h3>
                <p>Optimisez votre récolte avec les équipements adaptés.</p>
                <p>
                    <br>
                    <a href="#" class="button large ">Demander une expertise</a>
                </p>
            </div>
        </div>
    </div>
</section>

app/views/services/equipements/equipements_usages.html.erb
<section class="intro_page intro_equipements_usages">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <h1>Equipements usagés</h1>
            </div>
        </div>
    </div>
</section>
<div class="cap_black"></div>
<section class="content_page_dark">
    <div class="grid-container ">
        <h2>Rechercher un équipement</h2>
        <p>Nous disposons de beaucoup de modèles usagés qui peuvent répondre à vos besoins.
             </p>
             <br>

             <%= form_tag equipements_usages_path, method: :get do %>
             <ul class="menu">
                 <li>
                     <select class="liste_marques" id="brand" name="brand">
                         <option value="0">Toutes les marques</option>
                         <% Brand.all.each do |marque| %>
                            <% if params[:brand] && params[:brand].to_i == marque.id%>
                                <option value="<%= marque.id %>" selected><%= marque.name %></option>
                            <% else %>
                                <option value="<%= marque.id %>"><%= marque.name %></option>
                            <% end %>
                         <% end %>
                     </select>


                 </li>
                 <li><%= text_field_tag :search, params[:search], style:"width:500px",placeholder:"Rechercher un modèle ou une année..." %></li>               <li>
                 <%= button_tag "Search", name: nil, class: "button primary" do %>
                     <i class="fa fa-search"></i> &nbsp; Rechercher
                 <% end %>
             </li>
           </ul>
         <% end %>
    </div>
</section>

<section class="content_page">
    <div class="grid-container">


        <div class="grid-x grid-margin-x grid-margin-y">
            <% unless @equipments.nil? %>
                <% @equipments.each do |equipment| %>
                        <div class="cell large-4">
                            <div class="list_item_equipement">
                                <div class="list_item_equipement_image">
                                    <%= link_to equipements_usages_fiche_url(id: equipment.id ,marque:equipment.name.parameterize, annee:equipment.year) do %>
                                        <% if equipment.miniature.attached?  && Pathname.new(Rails.application.routes.url_helpers.rails_blob_url(equipment.miniature, only_path: true)).exist? %>
                                            <%= image_tag Rails.application.routes.url_helpers.rails_blob_url(equipment.miniature, only_path: false) %>
                                        <% else %>
                                            <%= image_tag("placeholder_miniature_equipement_usage.png") %>
                                        <% end %>
                                    <% end %>
                                </div>
                                <div class="list_item_equipement_info">
                                <h2><%= equipment.brand.name %> - <%= equipment.brand_model.name %> </h2>
                                        <strong>Année : </strong><%= equipment.year %>
                                        <br>
                                        <strong>heures/séparateur : </strong> <%= equipment.hour %>h / <%= equipment.separate_hour %>h
                                        <hr>
                                <% if !equipment.price.nil? %>
                                    <h3> <i class="fa fa-dollar-sign"></i> &nbsp; <%= number_to_currency(equipment.price) %></h3>
                                <% else %>
                                    <h3>Prix : Appelez-nous</h3>
                                <% end %>
                            </div>
                            </div>
                        </div>
                <% end %>


                <% if @search%>
                    <% if @equipments.empty?%>
                        <p>Votre recherche n'a donné aucun résultat...</p>
                    <% end %>
                <% end %>

            <% else %>
                <p>Pas d'équipements usagés pour le moment...</p>
            <% end %>
        </div>

    </div>
</section>

<section class="cta_page footer_cta_evaluation_equipement">
    <div class="grid-container">
        <div class="grid-x grid-margin-x grid-margin-y">
            <div class="cell large-12">
                <h3>Nous reprenons vos équipements usagés!</h3>
                <p>Selon l'état, nous tenons compte de votre équipement lors d'un achat d'un équipement usagé. Demandez une évaluation!</p>
                <p>
                    <br>
                    <%= link_to "Faire évaluer mon équipement", expertise_evaluation_equipement_url,class: "button large" %>
                </p>
            </div>
        </div>
    </div>
</section>

app/views/services/equipements/equipements_usages_fiche.html.erb
<section class="content_page content_page_equipement_usage bg_dust">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell large-12">
                <p>
                    <%= link_to "<< Retour aux équipements usagés", equipements_usages_url %>
                </p>
            </div>
            <div class="cell large-12 intro_fiche_equipement">
                <h1><%= @equipment.name %> - Année <%= @equipment.year %></h1>

                <% if !@equipment.price.nil? %>
                    <h3> <%= number_to_currency(@equipment.price) %> </h3>
                <% else %>
                    <h3>Appelez-nous</h3>
                <% end %>

                <p>
                    <%= @equipment.description %>
                </p>
            </div>

            <div class="cell large-8 photos_equipement_usage">
                <div class="owl-carousel owl-theme">
                    <% unless @equipment.photos.empty? %>
                        <% @equipment.photos.each_with_index do |photo,index| %>
                            <div class="item">
                                <% if Pathname.new(Rails.application.routes.url_helpers.rails_blob_url(photo, only_path: true)).exist? %>
                                    <%= image_tag Rails.application.routes.url_helpers.rails_blob_url(photo, only_path: false) %>
                                <% else %>
                                    <%= image_tag("placeholder_photos_equipement_usage.png") %>
                                <% end %>
                            </div>
                        <% end %>
                    <% else %>
                        <div class="item">
                            <% if @equipment.miniature.attached?  && Rails.application.routes.url_helpers.rails_blob_url(@equipment.miniature, only_path: true).nil? %>
                                <%= image_tag Rails.application.routes.url_helpers.rails_blob_url(@equipment.miniature, only_path: false) %>
                            <% else %>
                                <%= image_tag("placeholder_photos_equipement_usage.png") %>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="cell large-4 info_equipement_usage">

                <h3>Caractéristiques</h3>
                <p>
                <ul>
                    <li><strong>Marque : </strong><%= @equipment.brand.name unless @equipment.brand.nil? %></li>
                    <li><strong>Modèle : </strong><%= @equipment.brand_model.name unless @equipment.brand_model.nil? %></li>
                    <li><strong>Année : </strong><%= @equipment.year unless @equipment.year.nil? %></li>
                    <li><strong>Heures/Séparateur : </strong><%= @equipment.hour %> h / <%= @equipment.separate_hour %> h</li>
                    <li><strong>Motricité : </strong><%= @equipment.traction_type.name %></li>
                    <li><strong>Puissance : </strong><%= @equipment.power_type.name %></li>
                </ul>
                </p>
                <p><strong>Equipement d'échange</strong> : accepté <br>
                <strong>Possibilté de financement</strong> : oui </p>
                <br>
                <%= link_to "Contacter un vendeur", contact_url, class:"button large" %><br>
                <%= link_to "Echanger votre équipement", contact_echange_equipement_url(id: @equipment.id), class:"button secondary " %>

            </div>


        </div>
    </div>
</section>
<section class="cta_page">
    <div class="grid-container">
        <div class="grid-x grid-margin-y grid-margin-x">
            <div class="cell large-12">

            <h2>En achetant chez LAVOIE</h2>

        </div>
        </div>
    </div>
</section>


<script type="text/javascript">
$('.owl-carousel').owlCarousel({
    items:1,
    lazyLoad:true,
    loop:false,
    margin:10,
    nav: true,
    dots: false,
    navText : ["<i class='fa fa-chevron-left'></i>","<i class='fa fa-chevron-right'></i>"]
});
</script>