config/routes.rb
Rails.application.routes.draw do

    scope "/:locale", locale: /#{I18n.available_locales.join('|')}/ do


                    root 'page#index'

                    # PAGES
                    get 'entreprise', to: "page#entreprise"
                    get 'equipe', to: "page#equipe"

                    # Pages > Carriere
                    get 'carrieres', to: "page#carrieres"
                    get 'poste', to: "page#fiche_poste"

                    get 'candidature', to: "page#candidature"
                    post 'candidature', to: "contact#candidature_send", as: "candidature_send"
                    get 'candidature-spontanee', to: "page#candidature_spontanee"
                    post 'candidature-spontanee', to: "contact#candidature_spontanee_send", as: "candidature_spontanee_send"

                    # Contact
                    get 'contact/success', to: "contact#success"
                    get 'contact/error', to: "contact#error"
                    get 'contact', to: "contact#general"
                    post 'contact/general', to: "contact#general_send", as:"general_send"

                    get 'contact/acquisition-equipement',   to: "contact#acquisition_equipement"
                    post 'contact/acquisition-equipement',  to: "contact#acquisition_equipement_send",  as:"acquisition_equipement_send"
                    get 'contact/inspection-technique',     to: "contact#inspection_technique"
                    post 'contact/inspection-technique',    to: "contact#inspection_technique_send",    as:"inspection_technique_send"

                    get 'contact/evaluation-equipement',    to: "contact#evaluation_equipement"
                    post 'contact/evaluation-equipement',   to: "contact#evaluation_equipement_send",    as:"evaluation_equipement_send"

                    get 'contact/echange-equipement/(:id)', to: "contact#echange_equipement", as: "contact/echange/equipement/"
                    post 'contact/echange-equipement/(:id)',   to: "contact#echange_equipement_send",    as:"echange_equipement_send"


                    get 'contact/ajustement-equipement/',   to: "contact#ajustement_equipement"
                    post 'contact/ajustement-equipement',   to: "contact#ajustement_equipement_send",   as:"ajustement_equipement_send"
                    get 'contact/demande-financement',      to: "contact#demande_financement"
                    post 'contact/demande-financement',     to: "contact#demande_financement_send",     as:"demande_financement_send"
                    post 'contact/estimation-transport',    to: "contact#estimation_transport_send",    as:"estimation_transport_send"
                    get 'contact/recherche-approfondie',    to: "contact#recherche_approfondie"
                    post 'contact/recherche-approfondie',   to: "contact#recherche_approfondie_send",    as:"recherche_approfondie_send"

                    # SERVICES

                    get 'services', to: "services#index"
                    get 'financement', to: "page#financement"

                    # Services > Pieces
                    get 'pieces', to:"services#pieces"
                    get 'pieces/commande-libre', to:"services#pieces_commande_libre"
                    post 'pieces/commande', to:"services#pieces_commande_send", as: "pieces/commande"
                    get 'pieces/recherche-approfondie', to:"services#pieces_recherche_approfondie"


                    # Services > equipements
                    get 'equipements', to:"services#equipements"
                    get 'equipements/neufs', to:"services#equipements_neufs"
                    get 'equipements/neufs/marques/', to:"services#equipements_neufs_marques", as: 'equipements/neufs/marques'
                    get 'equipements/neufs/marque/(:marque)/', to:"services#equipements_neufs_marque", as: 'equipements/neufs/marque'
                    get 'equipements/neufs/type/(:type)', to:"services#equipements_neufs_type", as: 'equipements/neufs/type'
                    get 'equipements/neufs/culture/(:culture)/', to:"services#equipements_neufs_culture", as: 'equipements/neufs/culture'
                    get 'equipements/usages', to:"services#equipements_usages"
                    get 'equipements/usages/evaluation', to:"services#equipements_usages_evaluation"
                    get 'equipements/usages/fiche/(:id)/(:marque)/(:annee)', to:"services#equipements_usages_fiche", as: 'equipements/usages/fiche'

                    # Services > expertise-conseil
                    get 'expertise', to:"services#expertise_conseil"
                    get 'expertise/acquisition-equipement', to:"services#acquisition_equipement"
                    get 'expertise/inspection-technique', to:"services#inspection_technique"
                    get 'expertise/ajustement-equipement', to:"services#ajustement_equipement"
                    get 'expertise/evaluation-equipement', to:"services#evaluation_equipement"

                    # Services > Transport
                    get 'transport', to:"services#transport"
                    get 'transport/transport-machinerie', to:"services#transport_machinerie", as: "transport/transport-machinerie"
                    get 'transport/transport-international', to:"services#transport_international", as: "transport/transport-international"
                    get 'transport/transport-hors-normes', to:"services#transport_hors_normes", as: "transport/transport-hors-normes"

                    # LANDING PAGES

                    get '/landing/(:year)/(:landing_page)/', to: "page#landing_page", as: 'landing'

        
        end

        root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

        # Redirection de toutes les URL avec la locale (FR|EN)
        get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
                      constraints: { path: /(?!(#{I18n.available_locales.join("|")})\/).*/, subdomain: '' },
                      format: false




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

    # --------------------------------------------------------------------------
    # Views
    # --------------------------------------------------------------------------

    def success
    end

    # --------------------------------------------------------------------------

    def error
    end

    # --------------------------------------------------------------------------
    def general
    end

    # --------------------------------------------------------------------------

    def acquisition_equipement
    end

    # --------------------------------------------------------------------------

    def echange_equipement
        @equipment = Equipment.with_attached_photos.find(message_params[:id])
    end

    # --------------------------------------------------------------------------

    def ajustement_equipement
    end

    # --------------------------------------------------------------------------

    def inspection_technique
    end

    # --------------------------------------------------------------------------

    def recherche_approfondie
    end

    # --------------------------------------------------------------------------

    def evaluation_equipement
    end

    # --------------------------------------------------------------------------

    def demande_financement
    end

    # --------------------------------------------------------------------------

    def estimation_transport
    end

    # --------------------------------------------------------------------------
    # Actions
    # --------------------------------------------------------------------------

    def general_send
        @message = {
                        name: message_params[:name],
                        email: message_params[:email],
                        message: message_params[:message],
                        ip_address: request.remote_ip,
        }
        if ContactMailer.general(@message).deliver
            redirect_to contact_success_path
        else
            redirect_to contact_error_path
        end
    end

    # --------------------------------------------------------------------------

    def acquisition_equipement_send
        @message = {
                        name: message_params[:name],
                        email: message_params[:email],
                        phone: message_params[:phone],
                        forfait_acquisition: message_params[:forfait_acquisition],
                        type_equipement: message_params[:type_equipement],
                        message: message_params[:message],
                        ip_address: request.remote_ip,
        }
        if ContactMailer.acquisition_equipement(@message).deliver
            redirect_to contact_success_path
        else
            redirect_to contact_error_path
        end
    end

    # --------------------------------------------------------------------------

    def inspection_technique_send
        @message = {
                        name: message_params[:name],
                        email: message_params[:email],
                        phone: message_params[:phone],
                        forfait_inspection: message_params[:forfait_inspection],
                        message: message_params[:message],
                        ip_address: request.remote_ip,
        }
        if ContactMailer.inspection_technique(@message).deliver
            redirect_to contact_success_path
        else
            redirect_to contact_error_path
        end
    end
    # --------------------------------------------------------------------------

    def evaluation_equipement_send
        @message = {
                        name: message_params[:name],
                        email: message_params[:email],
                        phone: message_params[:phone],
                        message: message_params[:message],
                        type_evaluation: message_params[:type_evaluation],
                        ip_address: request.remote_ip,
        }
        if ContactMailer.evaluation_equipement(@message).deliver
            redirect_to contact_success_path
        else
            redirect_to contact_error_path
        end
    end
    # --------------------------------------------------------------------------

    def echange_equipement_send
        @equipment = Equipment.find(message_params[:id])
        @message = {
                    equipment: @equipment,
                    name: message_params[:name],
                    email: message_params[:email],
                    phone: message_params[:phone],
                    marque_equipement_echange: message_params[:marque_equipement_echange],
                    modele_equipement_echange: message_params[:modele_equipement_echange],
                    annee_equipement_echange: message_params[:annee_equipement_echange],
                    heures_equipement_echange: message_params[:heures_equipement_echange],
                    prix_equipement_echange: message_params[:prix_equipement_echange],
                    ip_address: request.remote_ip,
        }
        if ContactMailer.echange_equipement(@message, @equipment.brand.name, @equipment.brand_model.name, @equipment.year).deliver
            redirect_to contact_success_path
        else
            redirect_to contact_error_path
        end
    end

    # --------------------------------------------------------------------------

    def ajustement_equipement_send

        @message = {
                        name: message_params[:name],
                        email: message_params[:email],
                        phone: message_params[:phone],
                        forfait_ajustement: message_params[:forfait_ajustement],
                        type_equipement: message_params[:type_equipement],
                        message: message_params[:message],
                        ip_address: request.remote_ip,
        }
        if ContactMailer.ajustement_equipement(@message).deliver
            redirect_to contact_success_path
        else
            redirect_to contact_error_path
        end
    end

    # --------------------------------------------------------------------------

    def demande_financement_send
        @message = {
                        name: message_params[:name],
                        email: message_params[:email],
                        phone: message_params[:phone],
                        message: message_params[:message],
                        forfait_financement: message_params[:forfait_financement],
                        type_equipement: message_params[:type_equipement],
                        ip_address: request.remote_ip,
        }
        if ContactMailer.demande_financement(@message).deliver
            redirect_to contact_success_path
        else
            redirect_to contact_error_path
        end
    end

    # --------------------------------------------------------------------------

    def recherche_approfondie_send

        @message = {
                        name: message_params[:name],
                        email: message_params[:email],
                        phone: message_params[:phone],
                        forfait_recherche: message_params[:forfait_recherche],
                        message: message_params[:message],
                        ip_address: request.remote_ip,
        }
        if ContactMailer.recherche_approfondie(@message).deliver
            redirect_to contact_success_path
        else
            redirect_to contact_error_path
        end
    end

    # --------------------------------------------------------------------------

    def estimation_transport_send

        @message = {
                        name: message_params[:name],
                        email: message_params[:email],
                        message: message_params[:message],
                        phone: message_params[:phone],
                        type_chargement: message_params[:type_chargement],
                        hors_normes: message_params[:hors_normes],
                        location_start: message_params[:location_start],
                        location_end: message_params[:location_end],
                        ip_address: request.remote_ip,
        }
        if ContactMailer.estimation_transport(@message).deliver
            redirect_to contact_success_path
        else
            redirect_to contact_error_path
        end
    end

    # --------------------------------------------------------------------------

    def candidature_send

        @message = {
                        name: message_params[:name],
                        email: message_params[:email],
                        phone: message_params[:phone],
                        poste: message_params[:poste],
                        cv_candidature: message_params[:cv_candidature],
                        lettre_candidature: message_params[:lettre_candidature],
                        ip_address: request.remote_ip,
        }

        # Enregistrement des fichiers
        fichier_cv  = message_params[:cv_candidature]
        ext         = File.extname(fichier_cv.to_s)
        @message[:cv_filename]    = 'cv_'+ message_params[:name].underscore+"-"+Date.current.to_s+"-"+Time.now.to_i.to_s+ext
        File.open(Rails.root.join('public', 'uploads',@message[:cv_filename] ), 'wb') do |file|
           file.write(fichier_cv.read)
        end

        fichier_lettre  = message_params[:lettre_candidature]
        ext             = File.extname(fichier_lettre.to_s)
        @message[:lettre_filename]        = 'lettre_'+ message_params[:name].underscore+"-"+Date.current.to_s+"-"+Time.now.to_i.to_s+ext
        File.open(Rails.root.join('public', 'uploads', @message[:lettre_filename] ), 'wb') do |file|
           file.write(fichier_lettre.read)
        end

        if ContactMailer.candidature(@message).deliver

app/views/contact/acquisition_equipement.html.erb
<section class="content_page content_formulaire">
    <div class="grid-container">

        <div class="card_formulaire">
            <h2>Demande d'acquisition d'équipement</h2>
            <%= form_tag(acquisition_equipement_send_path, method: "post") do %>

                <%= label_tag(:name, "Votre nom") %>
                <%= text_field_tag :name, nil, {placeholder: "Votre nom", required: true} %>

                <div class="grid-x grid-margin-x">
                    <div class="cell large-6">
                        <%= label_tag(:email, "Votre courriel") %>
                        <%= email_field_tag :email, nil, {placeholder: "Votre adresse courriel", required: true} %>
                    </div>
                    <div class="cell large-6">
                        <%= label_tag(:phone, "Votre téléphone") %>
                        <%= telephone_field_tag :phone, nil, {placeholder: "Votre téléphone", required: true} %>
                    </div>
                </div>

                <%= label_tag(:message, "Forfait d'acquisition") %>
                <%=
                select_tag(:forfait_acquisition, options_for_select([
                    ['Acquisition à la carte'],
                    ['Acquisition clé en main'],
                    ]), :include_blank => '-- Choix du forfait --', required: true)
                %>

                <%= label_tag(:email, "Type d'équipement") %>
                <%= select(nil,:type_equipement, EquipmentType.all.collect {|p| [ p.name, p.name ] }, { :include_blank => "-- Choisir un type d'équipement --"}, required: true) %>

                <%= label_tag(:message, "Votre recherche") %>
                <%= text_area_tag :message,nil, {placeholder: "Précisez votre recherche",rows: 5, cols: 25, required: true} %>

                <%= submit_tag "Envoyer votre message", class:"button large"%>
            <% end %>
        </div>

    </div>
</section>

app/views/contact/ajustement_equipement.html.erb
<section class="content_page content_formulaire">
    <div class="grid-container">

        <div class="card_formulaire">

        <h2>Demande d'ajustement d'équipement</h2>

        <%= form_tag(ajustement_equipement_send_path, method: "post") do %>

            <%= label_tag(:name, "Votre nom") %>
            <%= text_field_tag :name, nil, {placeholder: "Votre nom", required: true} %>

            <div class="grid-x grid-margin-x">
                <div class="cell large-6">
                    <%= label_tag(:email, "Votre courriel") %>
                    <%= email_field_tag :email, nil, {placeholder: "Votre adresse courriel", required: true} %>
                </div>
                <div class="cell large-6">
                    <%= label_tag(:phone, "Votre téléphone") %>
                    <%= telephone_field_tag :phone, nil, {placeholder: "Votre téléphone", required: true} %>
                </div>
            </div>

            <div class="grid-x grid-margin-x">
                <div class="cell large-6">
                    <%= label_tag(:forfait_ajustement, "Type d'ajustement") %>
                    <%=
                        select_tag(:forfait_ajustement, options_for_select([
                            ['Ajustement Premium'],
                            ['Ajustement Haute-Performance'],
                          ]), :include_blank => '-- Choix du forfait --', required: true)
                    %>
                </div>
                <div class="cell large-6">
                    <%= label_tag(:type_equipement, "Type d'équipement") %>

                        <%=
                            select_tag(:type_equipement, options_for_select(
                            EquipmentType.all.collect {|p| [ p.name, p.name ]}
                            ), :include_blank => "-- Type d'équipement --", required: true)
                        %>

                </div>
            </div>

            <%= label_tag(:message, "Demandes particulières/précisions") %>
            <%= text_area_tag :message,nil, {placeholder: "Votre message",rows: 5, cols: 25, required: true} %>
            <br>

            <div class="grid-x flex_center">
                <div class="cell large-4">
                    <%= submit_tag "Envoyer votre message", class:"button large"%>
                </div>
                <div class="cell large-8">

                        <%= check_box(:tos, :accepted, { :class => 'tos_check', required: true }, "yes", "no") %> &nbsp; J'accepte les conditions ainsi que les frais éventuels rattachés à la demande.
                    <p>
                        <quote>
                            En cliquant sur j'accepte, vous autorisez l'entreprise LAVOIE Equipement Agricole
                            à enregister dans sa base de données les informations envoyées par ce formulaire et
                            à communiquer avec vous par la suite pour traiter votre demande.
                        </quote>
                    </p>
                </div>
            </div>
        </div>

        <% end %>
    </div>

</section>

app/views/contact/demande_financement.html.erb
<section class="content_page content_formulaire">
    <div class="grid-container">

        <div class="card_formulaire">


        <h2>Demande de financement</h2>

        <%= form_tag(demande_financement_send_path, method: "post") do %>

            <%= label_tag(:name, "Votre nom") %>
            <%= text_field_tag :name, nil, {placeholder: "Votre nom", required: true} %>

            <div class="grid-x grid-margin-x">
                <div class="cell large-6">
                    <%= label_tag(:email, "Votre courriel") %>
                    <%= email_field_tag :email, nil, {placeholder: "Votre adresse courriel", required: true} %>
                </div>
                <div class="cell large-6">
                    <%= label_tag(:phone, "Votre téléphone") %>
                    <%= telephone_field_tag :phone, nil, {placeholder: "Votre téléphone", required: true} %>
                </div>
            </div>
            <div class="grid-x grid-margin-x">
                <div class="cell large-6">
                    <%= label_tag(:forfait_financement, "Type de financement") %>
                    <%=
                        select_tag(:forfait_financement, options_for_select([
                            ['Crédit-Bail'],
                            ['Financement long terme'],
                          ]), :include_blank => '-- Type de financement --', required: true)
                    %>
                </div>
                <div class="cell large-6">
                    <%= label_tag(:type_equipement, "Type d'équipement") %>

                        <%=
                            select_tag(:type_equipement, options_for_select(
                            EquipmentType.all.collect {|p| [ p.name, p.name ]}
                            ), :include_blank => "-- Type d'équipement --", required: true)
                        %>

                </div>
            </div>
            <%= label_tag(:message, "Votre message") %>
            <%= text_area_tag :message,nil, {placeholder: "Votre message",rows: 10, cols: 25, required: true} %>

            <br>
            <div class="grid-x flex_center">
                <div class="cell large-4">
                    <%= submit_tag "Envoyer votre demande", class:"button large"%>
                </div>
                <div class="cell large-8">

                        <%= check_box(:tos, :accepted, { :class => 'tos_check', required: true }, "yes", "no") %> &nbsp; J'accepte les conditions ainsi que les frais éventuels rattachés à la demande.
                    <p>
                        <quote>
                            En cliquant sur j'accepte, vous autorisez l'entreprise LAVOIE Equipement Agricole
                            à enregister dans sa base de données les informations envoyées par ce formulaire et
                            à communiquer avec vous par la suite pour traiter votre demande.
                        </quote>
                    </p>
                </div>
            </div>
        <% end %>
    </div>
</div>

</section>

app/views/contact/echange_equipement.html.erb
<section class="content_page content_formulaire">
    <div class="grid-container">
<h2 class="center">Demande de valeur d'échange de votre équipement</h2>
            <div class="grid-x">

                <div class="cell large-12">
                    <div class="grid-x card_resume_usage_echange">
                        <div class="cell large-9">

                        <div class="card_resume_usage_echange_info">

                                <h3> <%= @equipment.name %></h3>

                            <% if !@equipment.price.nil? %>
                                <h3><i class="fa fa-comment-dollar"></i> &nbsp; <%= number_to_currency(@equipment.price) %> </h3>
                            <% else %>
                                <p>
                                    <i class="fa fa-comment-dollar"></i> &nbsp;
                                    <strong>Prix du sur demande</strong>
                                </p>
                            <% end %>
                            <ul>
                                <li> <strong>Année :</strong> <%= @equipment.year %></li>
                                <li><strong>Heures/Séparateur : </strong><%= @equipment.hour %> h / <%= @equipment.separate_hour %> h</li>
                                <li><strong>Motricité : </strong><%= @equipment.traction_type.name %></li>
                                <li><strong>Puissance : </strong><%= @equipment.power_type.name %></li>
                            </ul>
                        </div>
                        </div>
                        <div class="cell small-12 medium-12 large-3 flex_center">
                            <div class="card_resume_usage_echange_image">
                                <% if @equipment.miniature.attached? && Pathname.new(Rails.application.routes.url_helpers.rails_blob_url(@equipment.miniature, only_path: true)).exist? %>
                                    <%= image_tag Rails.application.routes.url_helpers.rails_blob_url(@equipment.miniature, only_path: false) %>
                                <% else %>
                                    <%= image_tag("placeholder_miniature_equipement_usage.png") %>
                                <% end %>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="cell large-12">
                    <div class="card_info_usage_echange">

                    <%= form_tag(echange_equipement_send_path(id: @equipment.id), method: "post") do %>

                        <%= label_tag(:name, "Votre nom") %>
                        <%= text_field_tag :name, nil, {placeholder: "Votre nom", required: true} %>

                        <div class="grid-x grid-margin-x">
                            <div class="cell large-6">
                                <%= label_tag(:email, "Votre courriel") %>
                                <%= email_field_tag :email, nil, {placeholder: "Votre adresse courriel", required: true} %>
                            </div>
                            <div class="cell large-6">
                                <%= label_tag(:phone, "Votre téléphone") %>
                                <%= telephone_field_tag :phone, nil, {placeholder: "Votre téléphone", required: true} %>
                            </div>
                        </div>

                        <br>

                        <h4>VOTRE ÉQUIPEMENT</h4>
                        <div class="grid-x grid-margin-x">
                            <div class="cell large-4">
                                    <%= label_tag(:modele_equipement_echange, "Marque") %>
                                <%= text_field_tag :marque_equipement_echange, nil, {placeholder: "Marque de votre équipement", required: true} %>
                            </div>
                            <div class="cell large-4">
                                <%= label_tag(:modele_equipement_echange, "Modèle") %>
                                <%= text_field_tag :modele_equipement_echange, nil, {placeholder: "Modèle de votre équipement", required: true} %>
                            </div>
                            <div class="cell large-4">
                                <%= label_tag(:annee_equipement_echange, "Année") %>
                                <%= text_field_tag :annee_equipement_echange, nil, {placeholder: "Année de votre équipement", required: true} %>
                            </div>
                        </div>
                        <div class="grid-x grid-margin-x">
                            <div class="cell large-6">
                                <%= label_tag(:heures_equipement_echange, "Heures d'utilisation") %>
                                <%= text_field_tag :heures_equipement_echange, nil, {placeholder: "Nombre d'heures d'utilisation", required: true} %>
                            </div>

                            <div class="cell large-6">
                                <%= label_tag(:prix_equipement_echange, "Prix souhaité pour votre équipement ($ CAD)") %>
                                <%= number_field_tag :prix_equipement_echange, nil, {placeholder: "Indiquez le prix pour votre équipement", required: true} %>
                            </div>
                        </div>

                        <br>

                        <div class="grid-x flex_center">
                            <div class="cell large-12">
                                <%= check_box(:tos, :accepted, { :class => 'tos_check', required: true }, "yes", "no") %> &nbsp; J'accepte les conditions ci-après <br>
                                <quote>
                                    En cliquant sur j'accepte, vous autorisez l'entreprise LAVOIE Equipement Agricole
                                    à enregister dans sa base de données les informations envoyées par ce formulaire et
                                    à communiquer avec vous par la suite pour traiter votre demande.
                                </quote>
                            </div>
                            <div class="cell large-12">
                                <br>
                                <%= submit_tag "Envoyer votre demande", class:"button large"%>
                            </div>
                        </div>

                    <% end %>
                </div>
                </div>
            </div>

    </div>
</section>



<script type="text/javascript">
$('.owl-carousel').owlCarousel({
    items:1,
    lazyLoad:true,
    loop:false,
    margin:10,
    nav: true,
    dots: false,
    navText : ["<i class='fa fa-chevron-left'></i>","<i class='fa fa-chevron-right'></i>"]
});
</script>

app/views/contact/error.html.erb
<section class="intro_page intro_contact_error">
    <div class="grid-container">
        <h1>Une erreur s'est produite...</h1>
    </div>
</section>
<div class="cap_white"></div>
<section class="content_page">
    <div class="grid-container center">
            <div class="cell">
        <h2>Un problème technique est survenue ! Nous vous invitons a réessayer ultérieurement.</h2>
        <br>
        <p><%= link_to "Revenir à la page d'accueil", root_url, class: "button large" %></p>
    </div>
    </div>
</section>